### ISSUE TITLE
Разночтения в разделении на алийот

### ISSUE THREAD

**Issue by michaelko58** [jewish-calendar/calendar#106]
1. Масей - хабадский обычай: шени в 33:50
Там же хамиши, когда две параши вместе
Шлиши: 33:54
Другой обычай: шени 33:11, шлиши 33:50
2, Дварим - хабадский обычай шени в 1:12, а не 1:11
3. Ваигаш по хабадски рвии 45:28  хамиши 46:8 (У нас по-хабадски). В других хумашим рвии 45:19
хамиши 45:28,  
4. Это правда шени/хамиши, но для полноты: в Хабаде начинают в Лех-лехо исроэль с  12:7, а у других по-другому

**Comment by dubinsky** [comment]
Когда закончишь, перепиши, пожалуйста, этот квиток на меня.

**Comment by dubinsky** [comment]
@michaelko58 

> В других хумашим ....?
Посмотри, как в других Хумашим, и впиши.

> у других по-другому
КАК?

**Comment by dubinsky** [comment]
2 и 3 сделал; скоро подам на визирование.

> Масей - хабадский обычай: шени в 33:50
> Там же хамиши, когда две параши вместе
> Шлиши: 33:54
> Другой обычай: шени 33:30, шлиши 33:50

Проверь, пожалуйста. У меня в файле - что, по несуществующему обычаю?

> в Хабаде начинают в Лех-лехо исроэль с  12:7, а у других по-другому
Ни хрена не понял; засунул в файл как TODO для тебя.
Или ты можешь внятно сказать, какая алия, глава и пасук по обоим обычаям?

**Comment by michaelko58** [comment]
Другой обычай Масей - моя ошибка.
Про Лех лехо - не обращай внимания, это разночтения в исроэль в шени/хамиши. Решили на этом пока не сосредотачиваться и ограничимся хабадским обычаем. Нет у меня под рукой нехабадского сидура.

**Comment by dubinsky** [comment]
Чтобы закончить с Масей (и закрыть этот квиток):
у меня в файле - шени (и хамиши когда вместе) 33:11, шлиши: 33:50, по всем обычаям.
Надо что-то поменять/добавить?

**Comment by michaelko58** [comment]
Думаю, оставить как обычай.
А дифолт - по нашему, когда шени и хамиши, когда две параши вместе в 33:50
Шлиши: 33:54

**Comment by dubinsky** [comment]
Хорошо.
