### ISSUE TITLE
Sdarot and haftarot

### ISSUE THREAD

**Issue by michaelko58** [jewish-calendar/calendar#88]
sidra: Bereishit,parasha:בראשית א,א-ו,ח, haftara: ישעיהו מב,ה-מג,י; ישעיהו מב,ה-כא; 
 sidra: Noach,parasha:בראשית ו,ט-יא,לב, haftara: ישעיהו נד,א-נה,ה; ישעיהו נד,א-י; 
 sidra: Lekh Lekha,parasha:בראשית יב,א-יז,כז, haftara: ישעיהו מ,כז-מא,טז; 
 sidra: Vayeira,parasha:בראשית יח,א-כב,כד, haftara: מלכים ב ד,א-לז; מלכים ב ד,א-כג; 
 sidra: Chayei Sarah,parasha:בראשית כג,א-כה,יח, haftara: מלכים א א,א-לא; 
 sidra: Toldot,parasha:בראשית כה,יט-כח,ט, haftara: מלאכי א,א-ב,ז; 
 sidra: Vayeitzei,parasha:בראשית כח,י-לב,ג, haftara: הושע יב,יג-יד,י; הושע יא,ז-יב,יב; 
 sidra: Vayishlach,parasha:בראשית לב,ד-לו,מג, haftara: הושע יא,ז-יב,יב; עובדיה א,א-כא; 
 sidra: Vayyeshev,parasha:בראשית לז,א-מ,כג, haftara: עמוס ב,ו-ג,ח; 
 sidra: Miqeitz,parasha:בראשית מא,א-מד,יז, haftara: מלכים א ג,טו-ד,א; 
 sidra: Vayigash,parasha:בראשית מד,יח-מז,כז, haftara: יחזקאל לז,טו-כח; 
 sidra: Vayechi,parasha:בראשית מז,כח-נ,כו, haftara: מלכים א ב,א-יב; 
 sidra: Shemot,parasha:שמות א,א-ו,א, haftara: ישעיהו כז,ו-כח,יג; כט,כב-כג; ירמיהו א,א-ב,ג; 
 sidra: Va'eira,parasha:שמות ו,ב-ט,לה, haftara: יחזקאל כח,כה-כט,כא; 
 sidra: Bo,parasha:שמות י,א-יג,טז, haftara: ירמיהו מו,יג-כח; 
 sidra: Beshalach,parasha:שמות יג,יז-יז,טז, haftara: שופטים ד,ד-ה,לא; שופטים ה,א-לא; 
 sidra: Yitro,parasha:שמות יח,א-כ,כב, haftara: ישעיהו ו,א-ז,ו; ט,ה-ו; ישעיהו ו,א-יג; 
 sidra: Mishpatim,parasha:שמות כא,א-כד,יח, haftara: ירמיהו לד,ח-כב; לג,כה-כו; 
 sidra: Terumah,parasha:שמות כה,א-כז,יט, haftara: מלכים א ה,כו-ו,יג; 
 sidra: Tetzaveh,parasha:שמות כז,כ-ל,י, haftara: יחזקאל מג,י-כז; 
 sidra: Ki Tisa,parasha:שמות ל,יא-לד,לה, haftara: מלכים א יח,א-לט; מלכים א יח,כ-לט; 
 sidra: Vayaqhel,parasha:שמות לה,א-לח,כ, haftara: מלכים א ז,מ-נ; מלכים א ז,יג-כו; 
 sidra: Pequdei,parasha:שמות לח,כא-מ,לח, haftara: מלכים א ז,נא-ח,כא; מלכים א ז,מ-נ; 
 sidra: Vayiqra,parasha:ויקרא א,א-ה,כו, haftara: ישעיהו מג,כא-מד,כג; 
 sidra: Tzav,parasha:ויקרא ו,א-ח,לו, haftara: ירמיהו ז,כא-ח,ג; ט,כב-כג; 
 sidra: Shemini,parasha:ויקרא ט,א-יא,מז, haftara: שמואל ב ו,א-ז,יז; שמואל ב ו,א-יט; 
 sidra: Tazria,parasha:ויקרא יב,א-יג,נט, haftara: מלכים ב ד,מב-ה,יט; 
 sidra: Metzora,parasha:ויקרא יד,א-טו,לג, haftara: מלכים ב ז,ג-כ; 
 sidra: Acharei,parasha:ויקרא טז,א-יח,ל, haftara: יחזקאל כב,א-טז; 
 sidra: Qedoshim,parasha:ויקרא יט,א-כ,כז, haftara: עמוס ט,ז-טו; יחזקאל כ,ב-כ; 
 sidra: Emor,parasha:ויקרא כא,א-כד,כג, haftara: יחזקאל מד,טו-לא; 
 sidra: Behar,parasha:ויקרא כה,א-כו,ב, haftara: ירמיהו לב,ו-כז; 
 sidra: Bechuqotai,parasha:ויקרא כו,ג-כז,לד, haftara: ירמיהו טז,יט-יז,יד; 
 sidra: Bamidbar,parasha:במדבר א,א-ד,כ, haftara: הושע ב,א-כב; 
 sidra: Nasso,parasha:במדבר ד,כא-ז,פט, haftara: שופטים יג,ב-כה; 
 sidra: Beha'alotkha,parasha:במדבר ח,א-יב,טז, haftara: זכריה ב,יד-ד,ז; 
 sidra: Shelach,parasha:במדבר יג,א-טו,מא, haftara: יהושוע ב,א-כד; 
 sidra: Qorach,parasha:במדבר טז,א-יח,לב, haftara: שמואל א יא,יד-יב,כב; 
 sidra: Chuqat,parasha:במדבר יט,א-כב,א, haftara: שופטים יא,א-לג; 
 sidra: Balaq,parasha:במדבר כב,ב-כה,ט, haftara: מיכה ה,ו-ו,ח; 
 sidra: Pinchas,parasha:במדבר כה,י-ל,א, haftara: מלכים א יח,מו-יט,כא; 
 sidra: Mattot,parasha:במדבר ל,ב-לב,מב, haftara: ירמיהו א,א-ב,ג; 
 sidra: Masei,parasha:במדבר לג,א-לו,יג, haftara: ירמיהו ב,ד-כח; ג,ד; ירמיהו ב,ד-כח; ד,א-ב; 
 sidra: Devarim,parasha:דברים א,א-ג,כב, haftara: ישעיהו א,א-כז; 
 sidra: Va'etchanan,parasha:דברים ג,כג-ז,יא, haftara: ישעיהו מ,א-כו; 
 sidra: Eiqev,parasha:דברים ז,יב-יא,כה, haftara: ישעיהו מט,יד-נא,ג; 
 sidra: Re'eh,parasha:דברים יא,כו-טז,יז, haftara: ישעיהו נד,יא-נה,ה; 
 sidra: Shoftim,parasha:דברים טז,יח-כא,ט, haftara: ישעיהו נא,יב-נב,יב; 
 sidra: Ki Teitzei,parasha:דברים כא,י-כה,יט, haftara: ישעיהו נד,א-י; 
 sidra: Ki Tavo,parasha:דברים כו,א-כט,ח, haftara: ישעיהו ס,א-כב; 
 sidra: Nitzavim,parasha:דברים כט,ט-ל,כ, haftara: ישעיהו סא,י-סג,ט; 
 sidra: Vayeilekh,parasha:דברים לא,א-ל, haftara: הושע יד,ב-י; יואל ב,טו-כז; הושע יד,ב-י; מיכה ז,יח-כ; 
 sidra: Ha'azinu,parasha:דברים לב,א-נב, haftara: שמואל ב כב,א-נא; 
 sidra: Vezot Haberakhah,parasha:דברים לג,א-לד,יב, haftara: יהושוע א,א-יח; יהושוע א,א-ט;

**Comment by dubinsky** [comment]
This list was not used as the only or the most authoritative source of data and may contain mistakes.
